[tool.poetry]
name = "integrated-platform"
version = "0.2.0"
description = "API-driven dynamic frontend with automated testing"
authors = ["Commander"]
readme = "README.md"
packages = [{include = "src"}]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "*"
typer = {extras = ["all"], version = "^0.16.0"}
ipython = "^8.20.0"
ipywidgets = "^8.1.1"
uvicorn = "^0.30.3"
openai-whisper = "^20231117"

[tool.poetry.group.dev.dependencies]
deptry = "^0.13.0"
ruff = "^0.5.5"


# 將測試工具定義為開發依賴 (dev-dependencies)
[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
httpx = "^0.23.0" # FastAPI 推薦的測試用 HTTP client
requests = "^2.32.3"
scipy = "^1.14.0"
[tool.pytest.ini_options]
pythonpath = ["src"]
markers = [
    "smoke: marks tests as smoke tests (fast, core functionality)"
]
