# ==============================================================================
# 鳳凰之心 - 資源監控設定 (Phoenix Heart - Resource Monitoring Settings)
# ==============================================================================
#
# 這個檔案集中管理所有與系統資源監控相關的參數。
# 我們的智慧型部署系統 (如 safe_installer.py) 將會讀取這裡的設定，
# 來決定如何在安裝與執行過程中進行資源檢查。
#
# 預設值設定得較為保守，以優先確保在低資源環境下的穩定性。
# 您可以根據實際的硬體環境調整這些參數。
#
# ------------------------------------------------------------------------------

resource_monitoring:
  # --- 磁碟空間監控 (Disk Space Monitoring) ---

  # 最小可用磁碟空間 (MB, integer)
  # 當可用磁碟空間低於此值 (單位為 MB) 時，將觸發警告或清理動作。
  min_disk_space_mb: 512

  # --- AI 模型載入策略 (AI Model Loading Strategy) ---

  # 可選策略: "memory" 或 "disk"
  # "memory": 預設選項。模型將被優先載入到記憶體中，以獲得最快的執行速度。
  # "disk": 當記憶體不足時，系統可能會考慮使用此策略，將模型的部分或全部
  #         緩存到磁碟上。 (此功能為未來擴展預留)
  model_storage_strategy: "memory"

  # --- 前端儀表板設定 (Dashboard Settings) ---

  # 儀表板刷新頻率 (秒, float)
  # 控制前端儀表板的更新頻率。較低的值會提供更即時的反應，但可能增加
  # CPU 負擔。建議值在 0.2 到 1.0 之間。
  monitor_refresh_seconds: 0.2

  # --- Colab 特定設定 (Colab Specific Settings) ---

  # 在 Colab 環境中，前端獲取代理 URL 的重試次數。
  # 此設定由 run/colab_runner.py 讀取並寫入動態的 config.json。
  colab_url_retries: 10
